language: cpp
os: linux
dist: bionic

cache:
  directories:
  - vst/download/

jobs:
  include:
  - name: "Linux arm64 test and build"
    arch: arm64-graviton2
    group: edge
    virt: lxd
    addons:
      apt:
        packages:
        - libjack-jackd2-dev
        - libsndfile1-dev
        - libcairo2-dev
        - libfontconfig1-dev
        - libx11-xcb-dev
        - libxcb-util-dev
        - libxcb-cursor-dev
        - libxcb-xkb-dev
        - libxkbcommon-dev
        - libxkbcommon-x11-dev
        - libxcb-keysyms1-dev
    install: .travis/download_cmake.sh
    script: .travis/script_test_and_build.sh

  - name: "Linux arm64 static plugins"
    arch: arm64-graviton2
    group: edge
    virt: lxd
    env:
    - INSTALL_DIR="sfizz-plugins-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}"
    - ENABLE_VST_PLUGIN=OFF
    - ENABLE_LV2_UI=OFF
    addons:
      apt:
        packages:
        - libjack-jackd2-dev
        - libsndfile1-dev
    install:
    - .travis/download_cmake.sh
    - .travis/download_static_libs.sh
    script: .travis/script_plugins.sh
    after_success: .travis/prepare_tarball.sh

  - name: "Discord Webhook"
    install: skip
    script: bash ${TRAVIS_BUILD_DIR}/.travis/discord_webhook.sh success

# Signal discord on failure
after_failure:
- bash ${TRAVIS_BUILD_DIR}/.travis/discord_webhook.sh failure

deploy:
  edge: true
  provider: releases
  file: "${INSTALL_DIR}.tar.gz"
  token:
    secure: jBIMWMPva8OazC8Wnqc2vqATa3exjvGDGvejEu6fgwt/BMDkgJCsJ7gS3ITpYFuO0HoHtLGfTVrFcZIE+agGVRdRGRni5xZRp5Vuf9hvLf8hCTaxkS/HYoliYYPp9FLY6J4yq9mp/R/QyGrwgssQEjhYlI2GL4+lJzt750AcmYibnQo2AMe5SSOp3q8KdLBG1vca1o1BZWBhW/S7l2hA1aJ7y1ytwm0ETIdrTZHxgfz7bqdqQcw/Ytqjm1rgzty6iQKX3B/InaZNB6CqXy6FoGLf771lery8nWJbjTjKYD4QK2NelExldyp1vrdHGvknWguFk+8vlQ16Dt0+R7Byr/LOPRLTCf/T+IehMQGtVA9/gjrkH8LqHy9oVFB+33p11gGu3h6hvg7yB6z3sSck0u4FHjrlpNd5XmmCsKQVQ9vI1cPPkVkbMHIewc7uOu+bD6cmotFj1vJ9UYesvN6n4siyCiPOIhgV9++bjcyiLqX3DWP5UWyZ9/VT8bz5VcxUdJnEYtdNPx4x5pRW4081VUjIf2EmHhQTrjb1iz6FAGwNU/fpefA8x+bBxXP9MkFFgU0tbCDKw2y6o0GOXX82mZr/IB0/DIBg7UllTzCBKTuiJQV1prFPlZLc6V22H5ozAXHgu3E+qNjvHoMsoYjGssX3+AYHwu8isBINo/gGo6Y=
  on:
    repo: "sfztools/sfizz"
    tags: true
    condition: ${TRAVIS_TAG} =~ ^v?[0-9]
